### ISSUE TITLE
打包失败！！！

### ISSUE THREAD

**Issue by giantchou** [belerweb/pinyin4j#6]
我想把pinyin4J放置到我的Solr6.1.0环境中使用，我的环境是这样的：
pinyin4j]# mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/maven3.3.9
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_92/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-642.el6.x86_64", arch: "amd64", family: "unix"

编译遇到的问题如下：
T E S T S
-------------------------------------------------------
Running net.sourceforge.pinyin4j.test.PinyinHelperTest
Tests run: 7, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.338 sec <<< FAILURE!
testToGwoyeuRomatzyhStringArray(net.sourceforge.pinyin4j.test.PinyinHelperTest)  Time elapsed: 0.231 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Expected: <null> but was: [Ljava.lang.String;@7a4f0f29
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.Assert.assertNull(Assert.java:268)
	at junit.framework.TestCase.assertNull(TestCase.java:438)
	at net.sourceforge.pinyin4j.test.PinyinHelperTest.testToGwoyeuRomatzyhStringArray(PinyinHelperTest.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0
.........中间部分内容略
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project pinyin4j: There are test failures.
[ERROR] 
[ERROR] Please refer to /data/solr-6.1.0/pinyin4j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
请问是不是pinyin4j目前不支持java8的缘故？

**Comment by yanton** [comment]
编译的时候跳过test试试，加上参数`-Dmaven.test.skip=true`

**Comment by giantchou** [comment]
加上参数-Dmaven.test.skip=true编译通过了，但是放置到Solr中提示以下错误：
org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core kwrecommid: Can't load schema  conf/schema.xml: Plugin init failure for [schema.xml] fieldType "text_pinyin": analyzer without class or tokenizer

我的schema.xml配置如下：

30    <fieldType name="text_pinyin" class="solr.TextField" positionIncrementGap="100">
 31       <analyzer type="index">  
 32         <filter class="com.shentong.search.analyzers.PinyinTransformTokenFilterFactory" minTermLenght="2" /> 
 33         <filter class="com.shentong.search.analyzers.PinyinNGramTokenFilterFactory" minGram="1" maxGram="20" />
 34       </analyzer>  
 35       <analyzer type="query">
 36          <filter class="com.shentong.search.analyzers.PinyinTransformTokenFilterFactory" minTermLenght="2" /> 
 37          <filter class="com.shentong.search.analyzers.PinyinNGramTokenFilterFactory" minGram="1" maxGram="20" />
 38       </analyzer>  
 39    </fieldType>

**Comment by giantchou** [comment]
<fieldType name="text_pinyin" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <filter class="net.sourceforge.pinyin4j.ChineseToPinyinResource" />
        <filter class="net.sourceforge.pinyin4j.PinyinRomanizationTranslator" />
      </analyzer>
      <analyzer type="query">
        <filter class="net.sourceforge.pinyin4j.ChineseToPinyinResource" />
        <filter class="net.sourceforge.pinyin4j.PinyinRomanizationTranslator" />
      </analyzer>
   </fieldType>
